apiVersion: apps/v1
kind: Deployment
metadata:
  name: istory
  labels:
    app: istory
spec:
  replicas: 3
  selector:
    matchLabels:
      app: istory
  template:
    metadata:
      labels:
        app: istory
    spec:
      containers:
        - image: dangtong/istory
          name: istory
          ports:
            - containerPort: 8080
          env:
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: istory-db-config
                  key: MYSQL_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: istory-db-secret
                  key: MYSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: istory-app-config
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 3
            periodSeconds: 10
