name: Gradle Package

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Source
        uses: actions/checkout@v3

      - name: 2. Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: 3. Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      # # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # # the publishing section of your build.gradle
      # - name: Publish to GitHub Packages
      #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      #   with:
      #     arguments: publish
      #   env:
      #     USERNAME: ${{ github.actor }}
      #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
